# Generated by Django 4.1.7 on 2023-03-22 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('published_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
